import image1 from '../assets/showcase1.jpg';
import image2 from '../assets/showcase2.jpg';
import image3 from '../assets/showcase3.jpg';
import image4 from '../assets/showcase4.jpg';
import image5 from '../assets/showcase5.jpg';
import image6 from '../assets/showcase6.jpg';
import image7 from '../assets/showcase7.jpg';
import image8 from '../assets/showcase8.jpg';
import image9 from '../assets/showcase9.jpg';
import image10 from '../assets/showcase10.jpg';
import image11 from '../assets/showcase11.jpg';
import image12 from '../assets/showcase12.jpg';
import image13 from '../assets/showcase13.jpg';
import image14 from '../assets/showcase14.jpg';
import image15 from '../assets/showcase15.jpg';
import image16 from '../assets/showcase16.jpg';
import image17 from '../assets/showcase17.jpg';
import image18 from '../assets/showcase18.jpg';
import image19 from '../assets/showcase19.jpg';
import image20 from '../assets/showcase20.jpg';
import image21 from '../assets/showcase21.jpg';
import image22 from '../assets/showcase22.jpg';
import image23 from '../assets/showcase23.jpg';
import image24 from '../assets/showcase24.jpg';
import image25 from '../assets/showcase25.jpg';


export const HotelDetail =[
    {
        id: 1,
        image: image1,
        title: 'Atliq Grands',
        desc: 'Escape to our luxurious resort and spa, nestled in the heart of breathtaking natural surroundings. Indulge in world-class amenities, rejuvenating spa treatments, and exquisite dining experiences. Experience the ultimate in relaxation and serenity at our resort.',

      },
      {
        id: 2,
        image: image2,
        title: 'Atliq Exotica',
        desc: 'Discover the charm of our seaside boutique hotel, located steps away from pristine sandy beaches. Immerse yourself in the tranquil coastal ambiance and enjoy breathtaking ocean views from our stylishly designed rooms. Experience coastal living at its finest.',

      },
      {
        id: 3,
        image: image3,
        title: 'Atliq City',
        desc: 'Unwind in our cozy mountain retreat lodge, surrounded by stunning peaks and lush forests. Experience the beauty of nature with hiking trails, mountain biking, and winter sports activities. Relax by the fireplace in our rustic yet elegant accommodations.',
      },
      {
        id: 4,
        image: image4,
        title: 'Atliq Blu',
        desc: 'Immerse yourself in the vibrant city life at our urban chic boutique hotel. Located in the heart of the bustling metropolis, our hotel offers stylish rooms, modern amenities, and easy access to shopping, dining, and entertainment venues. Experience the urban charm and sophistication.',

      },
      {
        id: 5,
        image: image5,
        title: 'Atliq Bay',
        desc: 'Step back in time at our historic inn and spa, where classic elegance meets modern comfort. Explore the rich history of the area and relax in our luxurious spa facilities. Indulge in gourmet dining and experience the timeless charm of our meticulously restored accommodations.',

      },
      {
        id: 6,
        image: image6,
        title: 'Atliq Palace',
        desc: 'Escape to our tropical paradise resort, located on a pristine island with white sandy beaches and crystal-clear turquoise waters. Immerse yourself in the tropical oasis with palm trees, exotic wildlife, and a range of water activities. Experience paradise like never before.',

      },
]


export const HotelRoomDetail = [
  {
    id: 1,
    pid: 16558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Delhi",
    images: image1,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 25,
    rt2_count: 35,
    rt3_count: 45,
    rt4_count: 55,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 2,
    pid: 16559,
    name: "Atliq Exotica",
    category: "Luxury",
    city: "Mumbai",
    images: image2,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 30,
    rt2_count: 41,
    rt3_count: 32,
    rt4_count: 18,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 3,
    pid: 16560,
    name: "Atliq City",
    category: "Business",
    city: "Delhi",
    images: image3,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 24,
    rt2_count: 34,
    rt3_count: 20,
    rt4_count: 7,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 4,
    pid: 16561,
    name: "Atliq Blu",
    category: "Luxury",
    city: "Delhi",
    images: image4,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 18,
    rt2_count: 24,
    rt3_count: 21,
    rt4_count: 10,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 5,
    pid: 16562,
    name: "Atliq Bay",
    category: "Luxury",
    city: "Delhi",
    images: image5,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 31,
    rt2_count: 43,
    rt3_count: 18,
    rt4_count: 6,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 6,
    pid: 16563,
    name: "Atliq Palace",
    category: "Business",
    city: "Delhi",
    images: image6,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 41,
    rt2_count: 38,
    rt3_count: 20,
    rt4_count: 18,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 7,
    pid: 17558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Mumbai",
    images: image7,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 19,
    rt2_count: 50,
    rt3_count: 27,
    rt4_count: 6,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 8,
    pid: 17559,
    name: "Atliq Exotica",
    category: "Luxury",
    city: "Mumbai",
    images: image8,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 32,
    rt2_count: 39,
    rt3_count: 16,
    rt4_count: 14,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 9,
    pid: 17560,
    name: "Atliq City",
    category: "Business",
    city: "Mumbai",
    images: image9,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 40,
    rt2_count: 45,
    rt3_count: 25,
    rt4_count: 13,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 10,
    pid: 17561,
    name: "Atliq Blu",
    category: "Luxury",
    city: "Mumbai",
    images: image10,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 26,
    rt2_count: 36,
    rt3_count: 19,
    rt4_count: 4,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 11,
    pid: 17562,
    name: "Atliq Bay",
    category: "Luxury",
    city: "Mumbai",
    images: image11,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 20,
    rt2_count: 30,
    rt3_count: 27,
    rt4_count: 6,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 12,
    pid: 17563,
    name: "Atliq Palace",
    category: "Business",
    city: "Mumbai",
    images: image12,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 35,
    rt2_count: 42,
    rt3_count: 22,
    rt4_count: 8,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 13,
    pid: 18558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Bangalore",
    images: image13,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 23,
    rt2_count: 29,
    rt3_count: 24,
    rt4_count: 5,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 14,
    pid: 18559,
    name: "Atliq Exotica",
    category: "Luxury",
    city: "Bangalore",
    images: image14,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 22,
    rt2_count: 32,
    rt3_count: 28,
    rt4_count: 8,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 15,
    pid: 18560,
    name: "Atliq City",
    category: "Business",
    city: "Bangalore",
    images: image15,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 28,
    rt2_count: 37,
    rt3_count: 29,
    rt4_count: 11,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 16,
    pid: 18561,
    name: "Atliq Blu",
    category: "Luxury",
    city: "Bangalore",
    images: image16,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 34,
    rt2_count: 47,
    rt3_count: 30,
    rt4_count: 9,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 17,
    pid: 18562,
    name: "Atliq Bay",
    category: "Luxury",
    city: "Bangalore",
    images: image17,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 33,
    rt2_count: 46,
    rt3_count: 26,
    rt4_count: 12,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 18,
    pid: 18563,
    name: "Atliq Palace",
    category: "Business",
    city: "Bangalore",
    images: image18,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 27,
    rt2_count: 33,
    rt3_count: 23,
    rt4_count: 7,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 19,
    pid: 19558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Chennai",
    images: image19,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 21,
    rt2_count: 27,
    rt3_count: 17,
    rt4_count: 4,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 20,
    pid: 19559,
    name: "Atliq Exotica",
    category: "Luxury",
    city: "Chennai",
    images: image20,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 29,
    rt2_count: 40,
    rt3_count: 31,
    rt4_count: 15,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 21,
    pid: 19560,
    name: "Atliq City",
    category: "Business",
    city: "Chennai",
    images: image21,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 37,
    rt2_count: 49,
    rt3_count: 33,
    rt4_count: 16,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 22,
    pid: 19561,
    name: "Atliq Blu",
    category: "Luxury",
    city: "Chennai",
    images: image22,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 36,
    rt2_count: 44,
    rt3_count: 25,
    rt4_count: 11,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 23,
    pid: 19562,
    name: "Atliq Bay",
    category: "Luxury",
    city: "Chennai",
    images: image23,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 39,
    rt2_count: 48,
    rt3_count: 32,
    rt4_count: 13,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 24,
    pid: 19563,
    name: "Atliq Palace",
    category: "Business",
    city: "Chennai",
    images: image24,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 38,
    rt2_count: 31,
    rt3_count: 21,
    rt4_count: 10,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  },
  {
    id: 25,
    pid: 20558,
    name: "Atliq Grands",
    category: "Luxury",
    city: "Hyderabad",
    images: image25,
    description: "",
    extras: [
      "p1",
      "p2",
      "p3",
      "p4",
      "p5",
      "p6"
    ],
    rt1_count: 42,
    rt2_count: 50,
    rt3_count: 36,
    rt4_count: 17,
    rt1_cost: 1000,
    rt2_cost: 2000,
    rt3_cost: 3000,
    rt4_cost: 4000,
  }
];
